name: bld_all

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Version tag to use: (bump must also be set to none to keep a specific version'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to use: (bump must also be set to none to keep a specific version'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string

jobs:

  bld_member_service:
    uses: ./.github/workflows/bld_docker_jib.yml
    secrets: inherit # pass all secrets
    with:
      context: member-service
      version_tag: ${{ inputs.version_tag }}
      bump: ${{ inputs.bump }}
      ref: ${{ inputs.ref }}

#   bld_token_authentication:
#     uses: ./.github/workflows/bld_docker.yml
#     secrets: inherit # pass all secrets
#     with:
#       docker_name: orcid/orcid-token-authentication-service
#       context: orcid-token-authentication-service
#       version_tag: ${{ inputs.version_tag }}
#       bump: ${{ inputs.bump }}
#       ref: ${{ inputs.ref }}
# 
#   bld_gateway:
#     uses: ./.github/workflows/bld_docker.yml
#     secrets: inherit # pass all secrets
#     with:
#       docker_name: orcid/orcid-gateway
#       context: orcid-gateway
#       version_tag: ${{ inputs.version_tag }}
#       bump: ${{ inputs.bump }}
#       ref: ${{ inputs.ref }}
# 
# 
# 
# 
# 
# 

