# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths-ignore:
      # Ignore workflow changes
      - '.github/**'

  pull_request:
    branches: [ main ]

  workflow_call:
  workflow_dispatch:

jobs:
  build-gateway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Gateway service
      run: mvn -B verify -Dangular.env=qa -Pprod --file gateway/pom.xml 
      
  build-user-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build User service
      run: mvn -B verify  -Pprod --file user-service/pom.xml
      
  build-assertion-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Assertion service
      run: mvn -B verify -Pprod --file assertion-service/pom.xml
      
  build-member-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Member service
      run: mvn -B verify -Pprod --file member-service/pom.xml
      
  build-discovery-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Discovery service
      run: mvn -B verify -Pprod --file discovery-service/pom.xml

